pipeline:
  identifier: Build_go_pipeline_sample_1722349271904
  name: Build go-pipeline-sample
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: harnessgitconnector
        repoName: go-pipeline-sample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    shell: Sh
                    command: |-
                      wget https://golang.org/dl/go1.20.4.linux-amd64.tar.gz
                      tar -C /usr/local -xzf go1.20.4.linux-amd64.tar.gz
                      export PATH=$PATH:/usr/local/go/bin
                      go version
                      go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotestreport
                  name: go_test_report
                  spec:
                    shell: Sh
                    command: "wget https://golang.org/dl/go1.20.4.linux-amd64.tar.gz\ntar -C /usr/local -xzf go1.20.4.linux-amd64.tar.gz\nexport PATH=$PATH:/usr/local/go/bin\ngo version\nexport GOBIN=/home/harness/go/bin\n\t\texport PATH=/home/harness/go/bin:$PATH\n\t\techo $PATH\n\t\tgo install github.com/jstemmer/go-junit-report/v2@latest\n\t\tgo test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml"
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - /harness/report.xml
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
        description: ""
        delegateSelectors:
          - docker-delegate
